
# ---------------------------------------------------------------
# Basic  Settings
# ---------------------------------------------------------------

title: Red Coast Base | çº¢å²¸åŸºåœ°  | æ¶ˆç­äººç±»æš´æ”¿ï¼Œä¸–ç•Œå±äºä¸‰ä½“ ğŸ¤Ÿ
version: 1.0.0
subtitle:
description:
author: Yimu
# support en, zh-Hans
# language: zh-Hans
language: en
date_format: '%Y-%m-%d'
favicon: /assets/favicon.ico

# site url
url:
baseurl: 
permalink: /:year/:month/:day/:title.html

# Pagination
# paginate: 10


exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "README_en.md","bower_components","bower.json","package.json","node_modules"]

#Assets
sass:
  sass_dir: _sass
  style: :compressed

# markdown
highlighter: rouge
highlight:
  line_number: true

###############################
# Menus
###############################
menu:
  home: /
  archives: /src/archives/
  about: /src/about/
  
menu_icons:
  enable: true
  home: home
  about: user
  categories: th
  schedule: calendar
  tags: tags
  archives: archive
 

# ---------------------------------------------------------------
# 3rd partyl lib
# ---------------------------------------------------------------

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

# Google Analytics
google_analytics: UAâ€”123057967-1


copyright:
  author: Yimu ã•ã¾Â®
  link: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  license_title: Â© Yimu ã•ã¾Â® 2007 - 2019 All Rights Reserved
  license_content: "Content on this site is licensed under a Creative Commons Attribution 4.0 International license"
  jekyll: "https://jekyllrb.com/"
  linode: "https://www.linode.com/"
  github: "https://github.com/FongRay/FongRay.github.io"
  last_gen: "Site last generated: April 26, 2019"