auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 忍把浮名，换了代码几行
url: http://www.fangr.tk
feed: /atom.xml
author_info: <a href="http://www.fangr.tk/">Fong Ray</a>
